### ISSUE TITLE
SEO research

### ISSUE THREAD

**Issue by sharonwarner** [cagov/benefits-screener#34]

**Comment by kalvinwang** [comment]
* Sitelinks: it turns out these are automatically generated by Google, we can't just have them added to a sitemap somehow
* Subdomain: we ended up going with a [subdomain of edd.ca.gov instead of a subdirectory](https://www.searchenginejournal.com/subdomains-vs-subfolders-seo/239795/t) for non-SEO reasons, which is worse for SEO since a subdomain is considered a new/separate domain, but it couldn't be helped
* Indexing: although we only have client-side routing, I confirmed that didn't prevent google from indexing our pages-- e.g. if you search for phrases that only occur on https://unemployment.edd.ca.gov/guide/how-to-apply (a url that only exists client-side; if you visit it, it’ll redirect to the first tab), [google has it already](https://unemployment.edd.ca.gov/guide/how-to-apply)
